# Using GITHUB_TOKEN, Variables, and Secrets

name: Open a new issue

on: workflow_dispatch

env:
  GLOBAL_VAR: "Global Context" # Workflow-level variable

jobs:
  open-new-issue:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job Context" # Job-level variable
    permissions:
      contents: read
      issues: write

    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue from ${{ env.GLOBAL_VAR }}" \
            --body "Created in ${{ env.JOB_VAR }}. Secret check: ${{ secrets.MY_ACTION_SECRET }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
